framework:
    default_locale: '%env(DEFAULT_LOCALE)%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(DEFAULT_LOCALE)%'
        default_path: '%kernel.project_dir%/translations'
        
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
