vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '/uploads/products/images'
            upload_destination: '%kernel.project_dir%/public/uploads/products/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
