
vich_uploader:
    db_driver: orm
    mappings:
        products:
            uri_prefix: 
            upload_destination: '%kernel.project_dir%/../htdocs/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
