vich_uploader:
  db_driver: orm # orm, mongodb, or propel
  mappings:
    user_profile_photos:
      uri_prefix: /uploads/user_profile_photos
      upload_destination: "%kernel.project_dir%/public/uploads/user_profile_photos"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
    products:
        uri_prefix: /images/products
        upload_destination: '%kernel.project_dir%/public/images/products'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer