download_pdf:
  path: /download-pdf
  controller: App\Controller\ReclamationController::downloadPdf

language_switcher:
    path: /language/{locale}
    controller: App\Controller\LanguageController::switchLocale

api_login_check:
    path: /api/login_check