# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    timezone: 'Africa/Tunis'
    locale: '%env(DEFAULT_LOCALE)%'

services:

    App\Repository\ProduitRepository:
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - App\Entity\Produit

    # default configuration for services in *this* file
# Register the EventParticipantCountValidator as a service
    App\Validator\EventParticipantCountValidator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: App\Validator\EventParticipantCountValidator }


    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Entity\:
        resource: '../src/Entity/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    ReCaptcha\ReCaptcha:
        arguments:
            - '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
            
    App\Menu\Builder:
        class: App\Menu\Builder
        autowire: true

    App\Service\StripeService:
        arguments:
            $stripePublicKey: '%env(STRIPE_PUBLIC_KEY)%'
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
  
    app.paginator:
        class: Knp\Component\Pager\PaginatorInterface
        arguments: ['@knp_paginator']

    Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'
    App\Locale\LocaleResolver:
        arguments: ['%env(DEFAULT_LOCALE)%']

    App\Controller\LanguageController:
        class: App\Controller\LanguageController
        autowire: true
        arguments:
            - '@session'
            - '@App\Locale\LocaleResolver'
        tags: ['controller.service_arguments']